### ISSUE TITLE
Rename main.css og main.js?

### ISSUE THREAD

**Issue by ArgTang** [ArgTang/Team-Warrior#28]
Er det noen standard for dette vi bør følge?
ser endel bruker stye.css eller websidenavn.css 
Jeg starta på å rename til index.css, men kan godt ta på meg å merge tilbake

**Comment by oleespen** [comment]
hehe vært litt fram og tilbake der,  JA gjør om :)

**Comment by ArgTang** [comment]
Ok, Done følger med i helgen og merger det som kommer
