### ISSUE TITLE
Navigasjonsbar

### ISSUE THREAD

**Issue by aleksanderaleksic** [ArgTang/Team-Warrior#9]

**Comment by ArgTang** [comment]
HOME about us og sponsorer med hover efx

**Comment by aleksanderaleksic** [comment]
Denne må gjøres om slik at teksten blir mindre når vinduets størrelse blir mindre

**Comment by ArgTang** [comment]
Sånn?

**Comment by aleksanderaleksic** [comment]
nei navbar teksten blir den samme uansett hvordan du skalerer vinduet

**Comment by ArgTang** [comment]
Prøv nå, linken til den nye css filen kom ikke med. Funker ikke like bra nå som det er fire elementer på menyen

**Comment by ArgTang** [comment]
Ny mobilnav, så denne er ferdig?
